name: inversiones
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  currency_text_input_formatter: ^2.1.10
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  intl: ^0.18.1
  local_auth: ^2.1.8
  local_auth_android: ^1.0.37
  lottie: ^2.7.0
  path_provider: ^2.1.1
  pattern_formatter: ^3.0.0
  permission_handler: ^11.0.1
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  uuid: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  lint: ^2.1.2

flutter:
  assets:
   - assets/

  uses-material-design: true

  
