name: inversiones
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  currency_text_input_formatter: ^2.1.10
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6
  http: ^1.1.0
  intl: ^0.18.1
  pattern_formatter: ^3.0.0
  screenshot: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  lint: ^2.1.2

flutter:


  uses-material-design: true

  
